BINS=compa_to_comp comp_lerp
LDLIBS=../comp.a ../../spline/spline.a ../../arc/arc.a ../../file/file.a ../../dlog/dlog.a ../../enums_map/enums_map.a ../../blaze/blaze.a -lm

all: $(BINS)

test: all

clean:
	rm -f $(BINS)

