BINS=splinea_to_spline spline_lerp
LDLIBS=../spline.a ../../arc/arc.a ../../file/file.a ../../dlog/dlog.a ../../enums_map/enums_map.a ../../blaze/blaze.a -lm

all: $(BINS)

test: all

clean:
	rm -f $(BINS)

