BINS=view_1
LDLIBS=../view.a ../../win/win.a ../../dlog/dlog.a ../../img/img.a ../../file/file.a ../../arc/arc.a ../../blaze/blaze.a ../../draw/draw.a -lSDL2 -lGL -lm

all: $(BINS)

test: all
	./view_1

clean:
	rm -f $(BINS)

